# Generated by Django 4.0.1 on 2022-01-19 03:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_active_alter_item_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-active', '-last_modified_at']},
        ),
        migrations.AlterField(
            model_name='item',
            name='active',
            field=models.BooleanField(default=False, help_text='an active item is visible in shop'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(db_index=True, max_length=250),
        ),
    ]
