# Generated by Django 4.0.1 on 2022-01-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_item_options_alter_item_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5.99, max_digits=6),
            preserve_default=False,
        ),
    ]
